config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server, at: '/cable'

  root 'projects#index'

  namespace :admins do
    resources :users
    resources :units
    resources :machinaries
  end

  resources :projects do
    member do
      get :new_assign
      post :assign
    end

    resources :milestones
    resources :bridges
    resources :dprs do 
      collection do 
        get :valid_dpr_date

        match "/(:date)/by_date" => "dprs#show", 
            :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
            :as => "by_date", via: :get

      end
    end
  end


end

app/controllers/dprs_controller.rb
class DprsController < ApplicationController
  before_action :authenticate_user!

  def new
    @project_dpr = current_user.projects.find(params[:project_id])

    @project_dpr.bridges.each do |bridge|
      bridge.dpr_bridges.build
    end

    @project_dpr.milestones.each do |milestone|
      milestone.dpr_milestones.build
    end

    Machinary.all.each do |machinary|
      @project_dpr.dpr_machinary_uses.build(:machinary_id => machinary.id) unless machinary.archieve
    end

    @project_dpr.dpr_labour_uses.build
    @project_dpr.dpr_activities.build
  end

  def create
    @project_dpr = current_user.projects.find(params[:project_id])

    @project_dpr.dpr_date = params[:report_date]

    respond_to do |format|
      if @project_dpr.dpr_submitted?(params[:date]) && @project_dpr.update(dpr_params)
        format.html { redirect_to projects_path, notice: 'dpr submitted successfully.' }
      else
        format.html { render :new, alert: 'something went wrong....' }
      end
    end
  end

  def edit
  end

  def update
  end

  def valid_dpr_date
    project = current_user.projects.find(params[:project_id])
    project.dpr_date = params[:date]
    
    respond_to do |format|

      unless project.dpr_submitted?(params[:date])         
        format.js { flash.now[:alert] =  "DPR already submitted for #{params[:date]}" }
      else
        format.js { render nothing: true, status: :ok }
      end
    end
  end

  def index
    @project = current_user.projects.find(params[:project_id])
    @dprs = @project.milestones.includes(:dpr_milestones).collect{|m| m.dpr_milestones.pluck(:dpr_date)}.flatten.uniq
  end

  def show
    @project = current_user.projects.find(params[:project_id])

    unless @project.dpr_submitted?(params[:date])
      @dpr_report = ProgressReport.new(@project.id, params[:date]).dpr_by_date
    else
      redirect_back(fallback_location: project_dprs_path, alert: 'DPR not submitted')
    end
  end

  private

  def dpr_params 
    params.require(:project).permit(
      milestones_attributes: [ 
        :id, 
        dpr_milestones_attributes: [ :progress, :activity ]
      ],
      bridges_attributes: [ 
        :id,
        dpr_bridges_attributes: [
                                  :excavation, 
                                  :sand_soiling_and_pcc,
                                  :top_slab_and_parapet,
                                  :face_wall_bottom,
                                  :activity,
                                  :labour_count
      ]],
      dpr_machinary_uses_attributes: [ :machinary_id, :count ],
      dpr_labour_uses_attributes: [
        :drain, :central_wall, :earth_work_in_filling, :blanketing
      ],
      dpr_activities_attributes: [ :description ]
    )
  end
end

app/helpers/dprs_helper.rb
module DprsHelper
end

app/views/dprs/index.html.erb
<div class="dpr-list">
  <div class="row">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Date</th>
          <th scope="col">DPR link</th>
        </tr>
      </thead>
      <tbody>
        <% @dprs.each_with_index do |dpr, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= @project.title %></td>
            <td><%= dpr %></td>
            <td><%= link_to "DPR for #{dpr}", by_date_project_dprs_path(@project.id, date: dpr) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dprs/new.html.erb
<div class="dpr-list">
  <div class="row">
    <div class="col-12">
      <%= form_with(model: @project_dpr, url: project_dprs_path(@project_dpr), local: true, method: :post, id: 'myform') do |f| %>
        <% if @project_dpr.errors.any? %>
          <div id="error_explanation">
            <ul>
            <% @project_dpr.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="row px-2">
          <span class="col-2">
            <b>Select DPR Date</b>
          </span>
          <div class="col-3">
            <%= date_field_tag :report_date, value = nil , options = {:max=> Date.today , id: 'dpr_date', 'data-url' => valid_dpr_date_project_dprs_path(@project_dpr), class: 'form-control' } %>
          </div>
        </div>
        <br>

        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Description</th>
              <th scope="col">Units</th>
              <th scope="col">Target Qty</th>
              <th scope="col">Today progress</th>
              <th scope="col">Todays' Activity</th>
            </tr>
          </thead>
          <tbody>
            <%= f.fields_for :milestones do |milestone_form| %>
              <%= milestone_form.fields_for :dpr_milestones do |dpr_form| %>

                <% if dpr_form&.object.new_record? %>
                  <tr>
                    <td><%= milestone_form&.object&.description %></td>
                    <td><%= milestone_form&.object&.unit&.name %></td>
                    <td><%= milestone_form&.object&.target %></td>
                    <td><%= dpr_form.text_field :progress, value: 0, class: 'col-4' %></td>
                    <td><%= dpr_form.text_area :activity %></td>
                  </tr>
                <% end %>
              <% end %>
            <% end %>
          </tbody>
        </table>
      
        <row>
          <div class="col-12 px-0">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Title</th>
                  <th scope="col">Span</th>
                  <th scope="col">Excavation(%)</th>
                  <th scope="col">Sand, Soiling and PCC(%)</th>
                  <th scope="col">Top Slab and Parapet(%)</th>
                  <th scope="col">Face wall Bottom(%)</th>
                  <th scope="col">Nos. of labour</th>
                  <th scope="col">Today's activity</th>
                </tr>
              </thead>

              <tbody>
                <%= f.fields_for :bridges do |bridge_form| %>
                  <%= bridge_form.fields_for :dpr_bridges do |dpr_bform| %>

                    <% if dpr_bform&.object&.new_record? %>
                      <tr>
                        <td><%= bridge_form&.object&.title %></td>
                        <td><%= bridge_form&.object&.span %></td>
                        <td ><%= dpr_bform.text_field :excavation, value: 0, class: 'col-8' %></td>
                        <td><%= dpr_bform.text_field :sand_soiling_and_pcc, value: 0, class: 'col-12' %></td>
                        <td><%= dpr_bform.text_field :top_slab_and_parapet, value: 0, class: 'col-10' %></td>
                        <td><%= dpr_bform.text_field :face_wall_bottom, value: 0, class: 'col-10' %></td>
                        <td><%= dpr_bform.text_field :labour_count, value: 0, class: 'col-12' %></td>
                        <td><%= dpr_bform.text_area :activity %></td>
                      </tr>
                    <% end %>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </row>

        <div class="row">
          <div class="col-4">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Machine</th>
                  <th scope="col">Machinary Used</th>
                </tr>
              </thead>
              <tbody>
                <%= f.fields_for :dpr_machinary_uses do |machinary_use| %>
                  <% if machinary_use&.object&.new_record? %>
                    <%= machinary_use.hidden_field :machinary_id, value: machinary_use&.object&.machinary.id %>
                    <tr>
                      <td><%= machinary_use&.object&.machinary&.name %></td>
                      <td><%= machinary_use.text_field :count, value: 0  %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="col-4">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Work</th>
                  <th scope="col">Labour Used</th>
                </tr>
              </thead>

              <tbody>
                <%= f.fields_for :dpr_labour_uses do |labour_use| %>
                  <% if labour_use&.object&.new_record? %>
                    <tr>
                      <td>Drain</td>
                      <td><%= labour_use.text_field :drain, value: 0  %></td>
                    </tr>

                    <tr>
                      <td>Central Wall</td>
                      <td><%= labour_use.text_field :central_wall, value: 0  %></td>
                    </tr>

                    <tr>
                      <td>Earth work in filling</td>
                      <td><%= labour_use.text_field :earth_work_in_filling, value: 0  %></td>
                    </tr>

                    <tr>
                      <td>Blanketing</td>
                      <td><%= labour_use.text_field :blanketing, value: 0  %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>

          <div class="col-4">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Other Activity</th>
                </tr>
              </thead>

              <tbody>
                <%= f.fields_for :dpr_activities do |labour_use| %>
                  <% if labour_use&.object&.new_record? %>
                    <tr>
                      <td><%= labour_use.text_area :description, class: 'col-12'%></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>        
        </div>
        <div class="form-actions text-center">
          <%= f.submit 'Submit DPR', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).on('change', '#dpr_date', function function_name(){
      $.ajax({
        type:"GET",
        url : $(this).data('url')+"?date="+this.value
      });
    });

  $('#myform').submit(function(event) {
    event.preventDefault(); //this will prevent the default submit

    if($('#dpr_date').val() == '')
    {
      alert('please select a DPR date.');
      return false
    }  
      
    $(this).unbind('submit').submit();
  })
</script>

app/views/dprs/show.html.erb
<br>
<div class="row">
  <div class="col-9">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Agency</th>
          <th scope="col">Agreement Number</th>
          <th scope="col">Deadline</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @project&.title %></td>
          <td><%= @project&.agency %></td>
          <td><%= @project&.contarct_agreement_number %></td>
          <td><%= @project&.deadline %></td>
        </tr>
      </tbody>
    </table>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="count">Milestones(#)</th>
          <th scope="col">Description</th>
          <th scope="col">Unit</th>
          <th scope="col">Target</th>
          <th scope="col">Upto Achieved (%)</th>
          <th scope="col">Today Progress</th>
          <th scope="col">Cummulative Qty</th>
          <th scope="col">Balance</th>
          <th scope="col">Total Uptodate</th>
          <th scope="col">Activity</th>
        </tr>
      </thead>
      <tbody>
        <% @dpr_report[:milestones].each_with_index do |milstone, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= milstone[:description] %></td>            
            <td><%= milstone[:unit] %></td>
            <td><%= milstone[:target] %></td>
            <td><%= milstone[:upto_percentage] %>%</td>
            <td class="
            custm_yellow_color"><%= milstone[:progress] %></td>
            <td><%= milstone[:cummulative] %></td>
            <td><%= milstone[:balance] %></td>
            <td><%= milstone[:upto_date] %></td>
            <td class="
            custm_yellow_color"><%= milstone[:activity] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Minor Bridges(#)</th>
          <th scope="col">Title</th>
          <th scope="col">Span</th>
          <th scope="col">Excavation(%)</th>
          <th scope="col">Sand filling, Soiling and PCC(%)</th>
          <th scope="col">Top Slab and Parapet(%)</th>
          <th scope="col">Face wall Bottom slab(%)</th>
          <th scope="col">Activity</th>
        </tr>
      </thead>
      <tbody>
        <% @dpr_report[:bridges].each_with_index do |bridge, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= bridge[:title] %></td>
            <td><%= bridge[:span] %></td>
            <td class="custm_yellow_color"><%= bridge[:excavation] %></td>
            <td class="custm_yellow_color"><%= bridge[:sand_soiling_and_pcc] %></td>
            <td class="custm_yellow_color"><%= bridge[:top_slab_and_parapet] %></td>
            <td class="custm_yellow_color"><%= bridge[:face_wall_bottom] %></td>
            <td class="custm_yellow_color"><%= bridge[:activity] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="row mx-0">
      <table class="table col-4">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Machine</th>
            <th scope="col">Machinary Used</th>
          </tr>
        </thead>
        <tbody>
          <% @dpr_report[:dpr_machinary_use].each_with_index do |bridge, index| %>
            <tr>
              <td><%= bridge[:machine_name] %></td>
              <td class="custm_yellow_color"><%= bridge[:count] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <table class="table col-4">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Work</th>
            <th scope="col">Labour Used</th>
          </tr>
        </thead>
        <tbody>
          <% dpr_labour_use = @dpr_report[:dpr_labour_use] %>
          <tr>
            <td>Drain</td>
            <td class="custm_yellow_color"><%= dpr_labour_use[:drain] %></td>
          </tr>
          <tr>
            <td>Central wall</td>
            <td class="custm_yellow_color"><%= dpr_labour_use[:central_wall] %></td>
          </tr>
          <tr>
            <td>Earth work in Filling</td>
            <td class="custm_yellow_color"><%= dpr_labour_use[:earth_work_in_filling] %></td>
          </tr>
          <tr>
            <td>Blanketing</td>
            <td class="custm_yellow_color"><%= dpr_labour_use[:blanketing] %></td>
          </tr>
        </tbody>
      </table>

      <table class="table col-4">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Other Activity</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @dpr_report[:other_activity] %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>



  <div class="col-3">
    <table class="table">
      <thead class='thead-dark'>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Team</th>
        </tr>
      </thead>
      <tbody>
        <% @project.users.each_with_index do |user, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= user&.full_name+" (#{user&.role.first})"  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dprs/valid_dpr_date.js.erb
<% if alert %>
  $("#flash").html('<%= j render partial: "shared/alert_banner" %>');
  $('#dpr_date').val(null)
<% end %>  