config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server, at: '/cable'

  root 'projects#index'

  namespace :admins do
    resources :users
    resources :units
    resources :machinaries
  end

  resources :projects do
    member do
      get :new_assign
      post :assign
    end

    resources :milestones
    resources :bridges
    resources :dprs do 
      collection do 
        get :valid_dpr_date

        match "/(:date)/by_date" => "dprs#show", 
            :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
            :as => "by_date", via: :get

      end
    end
  end


end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :users, -> { distinct }

  attr_accessor :user_id, :dpr_date

  before_create :permit_access

  has_many :milestones, dependent: :destroy
  accepts_nested_attributes_for :milestones, allow_destroy: true
  
  has_many :bridges, dependent: :destroy
  accepts_nested_attributes_for :bridges, allow_destroy: true

  has_many :dpr_machinary_uses, dependent: :destroy
  accepts_nested_attributes_for :dpr_machinary_uses, allow_destroy: true

  has_many :dpr_labour_uses, dependent: :destroy
  accepts_nested_attributes_for :dpr_labour_uses, allow_destroy: true

  has_many :dpr_activities, dependent: :destroy
  accepts_nested_attributes_for :dpr_activities, allow_destroy: true
    
  def dpr_submitted?(date)
    progress = milestones.joins(:dpr_milestones)
              .where('dpr_milestones.dpr_date = ?', date)
    
    progress.blank?
  end

  private

  def permit_access
    self.users << User.find(self.user_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin_permission, only: [:new, :create, :edit, :update, :assign, :new_assign ]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    set_accessor_attr

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'project created successfully.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project updated successfully.' }
      else
        format.html { render :edit }
      end
    end
  end

  def index
    @projects = current_user.projects
  end

  def show
    @project = current_user.projects.find(params[:id])
  end

  def new_assign
    @project = Project.find(params[:id])
  end

  def assign
    @project = Project.find(params[:id])

    unless assignment_params.blank?
      @project.users.delete_all
      @project.users << User.find(assignment_params[:users])
    end
    redirect_to projects_path, notice: 'Project assigned successfully.'
  end

  private

  def project_params
    params.require(:project).permit(:title, :agency, 
                                    :deadline, :begin_date,
                                    :contarct_agreement_number)
  end

  def set_accessor_attr
    @project.user_id = current_user.id
  end

  def assignment_params
    params.require(:assignments).permit(users:[])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_assign_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title text-center w-100 d-block" id="exampleModalLabel">Assign Project</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <div class="modal-body">
      <div class="row justify-content-center">
        <div class="col-8">
          <%= form_tag(assign_project_path(@project)) do %>

            <% User.all.each do |user| %>
              <div class="form-group">
                <div class="custom-control custom-checkbox">

                  <% if user.has_admin_permission? %>
                    <%= check_box_tag 'assignments_label[users][]', user.id, (checked = true if @project.users.include?(user)), { class: 'custom-control-input', id: "assignments_label_users_#{user.id}", disabled: true } %>

                    <%= label_tag "assignments_label[users][#{user.id}]", "#{user.full_name} [#{user.role.first}]", class: 'custom-control-label' %>

                    
                      <%= hidden_field_tag 'assignments[users][]', user.id -%>
                  <% else %>
                    <%= check_box_tag 'assignments[users][]', user.id, (checked = true if @project.users.include?(user)), { class: 'custom-control-input', id: "assignments_users_#{user.id}" } %>

                    <%= label_tag "assignments[users][#{user.id}]", "#{user.full_name} [#{user.role.first}]", class: 'custom-control-label' %>
                  <% end %>
                </div> 
              </div>
            <% end %>
            <div class="actions text-center">
              <%= submit_tag "Assign", class: 'btn btn-primary px-3' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
 <%= form_with(model: project, url: url, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, 'Title(*)' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :agency, 'Agency(*)' %>
    <%= form.text_field :agency, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :contarct_agreement_number %>
    <%= form.text_field :contarct_agreement_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :begin_date, 'Start date(*)' %>
    <%= form.date_field :begin_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :deadline %>
    <%= form.date_field :deadline, class: 'form-control' %>
  </div>
  <div class="actions text-center">
    <%= form.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/projects/edit.html.erb
<div class="row justify-content-center mt-5">
  <div class="col-6">
    <h1 class="text-center">Edit Project</h1>
    <%= render 'form', project: @project, url: project_path %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="dpr-list">
  <div class="row">
    <div class="col-6">
      <br/>
      <% if current_user.has_admin_permission? %>
        <div class="col">
          <%= link_to 'New Project', new_project_path, class: 'btn btn-outline-primary' %>
        </div>
      <% end %>
    </div>
  </div>
  <br>
  <div class="row">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Agency</th>
          <th scope="col">BeginDate</th>
          <th scope="col">Deadline</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each_with_index do |project, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= project&.title %></td>
            <td><%= project&.agency %></td>
            <td><%= project&.begin_date %></td>
            <td><%= project&.deadline %></td>
            <td>
              <%= link_to 'Submit DPR', new_project_dpr_path(project), class: 'btn btn-secondary' %>
              <%= link_to 'Progress Report', project_path(project), class: 'btn btn-secondary' %>
              <%= link_to 'All DPRs', project_dprs_path(project), class: 'btn btn-secondary' %>
              <% if current_user.has_admin_permission? %>
                <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-secondary' %>
                <%= link_to 'Assign Team', new_assign_project_path(project), class: 'btn btn-secondary', remote: true %>              
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="assign-project-modal" tabindex="-1" role="dialog" aria-labelledby="bridge-modal" aria-hidden="true">

</div>

app/views/projects/new.html.erb
<div class="row justify-content-center mt-5">
  <div class="col-6">
    <h1 class="text-center">New Project</h1>
    <%= render 'form', project: @project, url: projects_path %>
  </div>
</div>

app/views/projects/new_assign.js.erb
$('#assign-project-modal').html("<%= j render partial: 'assign_form' %>")

$('#assign-project-modal').modal('toggle');

app/views/projects/show.html.erb
<br>
<div class="row">
  <div class="col-9">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Agency</th>
          <th scope="col">Agreement Number</th>
          <th scope="col">Deadline</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @project&.title %></td>
          <td><%= @project&.agency %></td>
          <td><%= @project&.contarct_agreement_number %></td>
          <td><%= @project&.deadline %></td>
          <td>
            <% if current_user.has_admin_permission? %>
              <%= link_to 'Add Milstone', new_project_milestone_path(@project), remote: true, class: 'btn btn-secondary' %> 
              <%= link_to 'Add Bridge', new_project_bridge_path(@project), remote: true, class: 'btn btn-secondary' %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Milestones(#)</th>
          <th scope="col">Description</th>
          <th scope="col">Unit</th>
          <th scope="col">Target</th>
          <th scope="col">Upto Achieved (%)</th>
          <th scope="col">Cummulative Qty</th>
          <th scope="col">Balance</th>
          <th scope="col">Total Uptodate</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @project.milestones.each_with_index do |milstone, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= milstone&.description %></td>
            <td><%= milstone&.unit&.name %></td>
            <td><%= milstone&.target %></td>
            <td><%= milstone&.achieved_till_date %></td>
            <td><%= milstone&.cummulative_till_date %></td>
            <td><%= milstone&.balance_till_date %></td>
            <td><%= milstone&.total_till_date %></td>
            <td>
              <% if current_user.has_admin_permission? %>
                <%= link_to 'Edit', edit_project_milestone_path(@project, milstone), remote: true, class: 'btn btn-secondary' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Minor Bridges(#)</th>
          <th scope="col">Title</th>
          <th scope="col">Span</th>
          <th scope="col">Excavation(%)</th>
          <th scope="col">Sand filling, Soiling and PCC(%)</th>
          <th scope="col">Top Slab and Parapet(%)</th>
          <th scope="col">Face wall Bottom slab(%)</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @project.bridges.each_with_index do |bridge, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= bridge&.title %></td>
            <td><%= bridge&.span %></td>
            <td><%= bridge&.excavation_till_date %></td>
            <td><%= bridge&.sand_soiling_and_pcc_till_date %></td>
            <td><%= bridge&.top_slab_and_parapet_till_date %></td>
            <td><%= bridge&.face_wall_bottom_till_date %></td>
            <td>
              <% if current_user.has_admin_permission? %>
                <%= link_to 'Edit', edit_project_bridge_path(@project, bridge), remote: true, class: 'btn btn-secondary' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-3">
    <table class="table">
      <thead class='thead-dark'>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Team</th>
        </tr>
      </thead>
      <tbody>
        <% @project.users.each_with_index do |user, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= user&.full_name+" (#{user&.role.first})"  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="add_milestone" tabindex="-1" role="dialog" aria-labelledby="add_milestone" aria-hidden="true">

</div>

<!-- Modal -->
<div class="modal fade" id="bridge-modal" tabindex="-1" role="dialog" aria-labelledby="bridge-modal" aria-hidden="true">

</div>