config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server, at: '/cable'

  root 'projects#index'

  namespace :admins do
    resources :users
    resources :units
    resources :machinaries
  end

  resources :projects do
    member do
      get :new_assign
      post :assign
    end

    resources :milestones
    resources :bridges
    resources :dprs do 
      collection do 
        get :valid_dpr_date

        match "/(:date)/by_date" => "dprs#show", 
            :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
            :as => "by_date", via: :get

      end
    end
  end


end

app/models/bridge.rb
class Bridge < ApplicationRecord
  belongs_to :project

  has_many :dpr_bridges, dependent: :destroy
  accepts_nested_attributes_for :dpr_bridges, allow_destroy: true


  def excavation_till_date(date = Date.today)
    dpr_bridges.where('dpr_date >= ?', date).order('dpr_date DESC')&.first&.excavation || 0
  end

  def sand_soiling_and_pcc_till_date(date = Date.today)
    dpr_bridges.where('dpr_date >= ?', date).order('dpr_date DESC')&.first&.sand_soiling_and_pcc || 0 
  end

  def top_slab_and_parapet_till_date(date = Date.today)
    dpr_bridges.where('dpr_date >= ?', date).order('dpr_date DESC')&.first&.top_slab_and_parapet || 0
  end

  def face_wall_bottom_till_date(date = Date.today)
    dpr_bridges.where('dpr_date >= ?', date).order('dpr_date DESC')&.first&.face_wall_bottom || 0
  end

end

app/controllers/bridges_controller.rb
class BridgesController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin_permission
  
  def new
    project = Project.find(params[:project_id])
    @bridge = project.bridges.build
  end


  def create
    project = Project.find(params[:project_id])
    @bridge = project.bridges.build(bridge_params)

    respond_to do |format|
      if @bridge.save
        format.js { redirect_to project_path(project), notice: 'Bridge added successfully.' }
      else
        format.js { render :new }
      end
    end
  end

  def edit
    @bridge = Bridge.find(params[:id])
  end

  def update
    project = Project.find(params[:project_id])
    @bridge = project.bridges.find(params[:id])

    respond_to do |format|
      if @bridge.update(bridge_params)
        format.js { redirect_to project_path(project), notice: 'Bridge updated successfully.' }
      else
        format.js { render :edit }
      end
    end
  end

  def show
  end

  private

  def bridge_params
    params.require(:bridge).permit(:title, :span)
  end

end

app/helpers/bridges_helper.rb
module BridgesHelper
end

app/views/bridges/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel"><%= title %></h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <div class="modal-body">
      <%= form_for(bridge, url: url, method: method_name, local: false, remote: true) do |form| %>
        <% if bridge.errors.any? %>
          <div id="error_explanation">
            <ul>
            <% bridge.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group" id="follow_up_date">
          <%= form.label :title %>
          <%= form.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group" id="follow_up_date">
          <%= form.label :span %>
          <%= form.text_field :span, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= form.submit class: 'btn btn-primary submit-button' %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/bridges/edit.js.erb
$('#bridge-modal').html("<%= j render partial: 'form',  :locals => { :url => project_bridge_path(@bridge.project, @bridge ), :method_name => :PUT, :bridge => @bridge, title: 'Edit bridge' } %>")

<% if @bridge.errors.blank? %>
  $('#bridge-modal').modal('toggle');
<% end %>

app/views/bridges/new.js.erb
$('#bridge-modal').html("<%= j render partial: 'form', locals: { url: project_bridges_path(@bridge.project), :method_name => :post, :bridge => @bridge, title: 'New bridge'  } %>")

<% if @bridge.errors.blank? %>
  $('#bridge-modal').modal('toggle');
<% end %>