config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server, at: '/cable'

  root 'projects#index'

  namespace :admins do
    resources :users
    resources :units
    resources :machinaries
  end

  resources :projects do
    member do
      get :new_assign
      post :assign
    end

    resources :milestones
    resources :bridges
    resources :dprs do 
      collection do 
        get :valid_dpr_date

        match "/(:date)/by_date" => "dprs#show", 
            :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
            :as => "by_date", via: :get

      end
    end
  end


end

app/models/unit.rb
class Unit < ApplicationRecord

  validates :name, presence: true
  validates_uniqueness_of :name
end

app/controllers/admins/units_controller.rb
class Admins::UnitsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin_permission

  def index
    @units = Unit.where(archieve: false).or(Unit.where(archieve: nil))
  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to admins_unit_path(@unit), notice: 'Unit created successfully.' }
      else
        format.html { render :new }
      end
    end
  end

  def  edit
    @unit = Unit.find(params[:id])
  end

  def  update
    @unit = Unit.find(params[:id])

    respond_to do |format|

      if @unit.update(user_params)
        format.html { redirect_to admins_user_path(@unit), notice: 'user updated successfully.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def destroy
    @unit = Unit.find(params[:id])

    @unit.update(archieve: true)
    respond_to do |format|
      format.html { redirect_to admins_unit_path, notice: "Unit destroyed successfully." }
    end
  end

  private

  def unit_params
    params.require(:unit).permit(:name)
  end

end

app/helpers/admins/units_helper.rb
module Admins::UnitsHelper
end

app/views/admins/units/_form.html.erb
<%= form_with(model: unit, url: url, local: true, method: method) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/admins/units/edit.html.erb
<h1>Edit Unit</h1>
<%= render 'form', unit: @unit, url: admins_unit_path(@unit), method: :put %>

app/views/admins/units/index.html.erb
<div class="dpr-list">
  <div class="row">
    <div class="col-6">
      <br/>
      <div class="col">
        <%= link_to 'New Unit', new_admins_unit_path, class: 'btn btn-outline-primary' %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @units.each_with_index do |unit, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= unit&.name&.upcase %></td>
            <td>
              <%= link_to 'Edit', edit_admins_unit_path(unit),class: 'btn btn-secondary' %> 
              <%= link_to 'Delete', admins_unit_path(unit), method: :DELETE, remote: true, class: 'btn btn-secondary' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/units/new.html.erb
<div class="container">
  <h1>New Unit</h1>
  <%= render 'form', unit: @unit, url: admins_units_path, method: :post %>
</div>

app/views/admins/units/show.html.erb
<div class="container">
  <div class="teacher-name" style="padding-top:20px;">

    <div class="row" style="margin-top:0px;">
    <div class="col-md-9">
      <h2 style="font-size:38px"><strong><%= @unit&.name %></strong></h2>
    </div>
    <div class="col-md-3">
      <div class="button" style="float:right;">
        <%= link_to 'Delete', admins_unit_path(@unit), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-primary btn-sm' %>
      </div>
      <div class="button" style="float:right;">
        <%= link_to 'Edit', edit_admins_unit_path(@unit), class: 'btn btn-outline-primary btn-sm' %>
      </div>
    </div>
    </div>
  </div>

  <div class="row" style="margin-top:20px;">
    <div class="col-md-6">
    </div>

    <div class="col-md-6">

      <h5>
        Name: <%= @unit&.name %>
      </h5>
    </div>
  </div>
</div>